[package]
name = "soundio-sys"
version = "0.1.2"
edition = "2021"
description = "Unsafe Rust bindings for libsoundio"
repository = "https://github.com/Nyquist-Studio/soundio-sys"
license = "MIT"

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"
